# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Deta
      # You may pin to the exact commit or the version.
      # uses: BogDAAAMN/deta-deploy-action@b1b7b9a17f5ff9decd2943afa4dad48aa645e5f1
      uses: BogDAAAMN/deta-deploy-action@v1.0.0
      with:
        # Deta access token
        deta-access-token: ${{ secrets.DETA_TOKEN }}
        # Deta micro name
        deta-name: 'neno'
        # Deta project name
        deta-project: 'default'
